apiVersion: v1
kind: PersistentVolume
metadata:
  name: kdesnew-pv-volume
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/host_mnt/c/kd/dev/bd"