apiVersion: v1
kind: PersistentVolume
metadata:
  name: kdmqtt-pv-data
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
     path: "/run/desktop/mnt/host/c/kd/dev/bd/volumes/mosquitto/data"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - docker-desktop