persistence:
  ## database data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  storageClass: "local-storage"
  size: 100Mi

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  #
  # KD - If we specify CPU requests as 100m, K8s allocates a minimum CPU of 100m, even
  # though MQTT might be idle. If we leave requests empty as {}, then it allocates a minimum
  # of 0. That leaves the K8s scheduler with a little more available CPU that it can
  # allocate to other Pods. 
   limits: {}
#     cpu: 100m
#     memory: 128Mi
   requests: {}
#     cpu: 100m
#     memory: 128Mi