spring:
  # Ignore JDBC Dependency. We are putting 3 applicatons in the same project so they all pick up the
  # JDBC Depdendency, but this application doesn't need it.
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  # Discovery Server Dashboard uses FreeMarker.  Don't want Thymeleaf templates
  thymeleaf:
    enabled: false     # Disable Thymeleaf 
  datasource:
    type: org.springframework.jdbc.datasource.SimpleDriverDataSource

# Configure this Discovery Server
eureka:
    instance:
        hostname: localhost
    client:  # Not a client, don't register with yourself (unless running
             # multiple discovery servers for redundancy)
        registerWithEureka: false
        fetchRegistry: false

# HTTP (Tomcat) port for Eureka server to listen
server:
    port: 1111
