apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: kd-py-nested-json
  namespace: spark-app
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "gcr.io/spark-operator/spark-py:v3.0.0"
  imagePullPolicy: Always
  mainApplicationFile: local:///tmp/dev/pysrc/KDNestedJson.py
  sparkVersion: "3.0.0"
  restartPolicy:
    type: Never
  volumes:
    - name: "dev"
      hostPath:
        path: "/run/desktop/mnt/host/c/kd/dev/bd/spark/devp"
        type: Directory
  driver:
    # 'cores' takes only integer values, with a minimum of 1 which requires
    # 1 full CPU. Use 'coreRequest' instead which takes fractional values.
    # For more info https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/581 
#    cores: 1
    coreRequest: 100m
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.0.0
    serviceAccount: sparkop-spark
    volumeMounts:
      - name: "dev"
        mountPath: "/tmp/dev"
  executor:
#    cores: 1
    coreRequest: 100m
    instances: 1
    memory: "512m"
    labels:
      version: 3.0.0
    volumeMounts:
      - name: "dev"
        mountPath: "/tmp/dev"
