apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: kd-py-channel-kafka
  namespace: spark-app
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "gcr.io/spark-operator/spark-py:v3.0.0"
  imagePullPolicy: Always
  mainApplicationFile: local:///tmp/dev/pydemo/demo.py
  arguments: 
    # - "kafka.kd-confluent.svc.cluster.local:9071"
    # - "json_spark"
    - "/tmp/data"
  deps:
    packages:
      - org.apache.spark:spark-sql-kafka-0-10_2.12:3.0.0
  sparkVersion: "3.0.0"
  sparkConf:
    spark.jars.packages: "org.apache.spark:spark-sql-kafka-0-10_2.12:3.0.0"
    spark.jars.ivy: "/tmp/ivy"
    spark.jars: "local:///tmp/ivy/jars/org.apache.spark_spark-sql-kafka-0-10_2.12-3.0.0.jar,\
      local:///tmp/ivy/jars/org.apache.kafka_kafka-clients-2.4.1.jar,\
      local:///tmp/ivy/jars/org.apache.commons_commons-pool2-2.6.2.jar,\
      local:///tmp/ivy/jars/org.xerial.snappy_snappy-java-1.1.7.5.jar,\
      local:///tmp/ivy/jars/com.github.luben_zstd-jni-1.4.4-3.jar,\
      local:///tmp/ivy/jars/org.lz4_lz4-java-1.7.1.jar,\
      local:///tmp/ivy/jars/org.slf4j_slf4j-api-1.7.30.jar,\
      local:///tmp/ivy/jars/org.spark-project.spark_unused-1.0.0.jar,\
      local:///tmp/ivy/jars/org.apache.spark_spark-token-provider-kafka-0-10_2.12-3.0.0.jar"
  restartPolicy:
    type: Never
  volumes:
    - name: "data"
      hostPath:
        path: "/run/desktop/mnt/host/c/kd/dev/bd/spark/data"
        type: Directory
    - name: "dev"
      hostPath:
        path: "/run/desktop/mnt/host/c/kd/dev/bd/spark/devp"
        type: Directory
    - name: "ivy"
      hostPath:
        path: "/run/desktop/mnt/host/c/kd/dev/bd/volumes/spark/ivy"
        type: Directory
  driver:
    # 'cores' takes only integer values, with a minimum of 1 which requires
    # 1 full CPU. Use 'coreRequest' instead which takes fractional values.
    # For more info https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/581 
#    cores: 1
    coreRequest: 100m
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.0.0
    serviceAccount: sparkop-spark
    volumeMounts:
      - name: "data"
        mountPath: "/tmp/data"
      - name: "dev"
        mountPath: "/tmp/dev"
      - name: "ivy"
        mountPath: "/tmp/ivy"
  executor:
#    cores: 1
    coreRequest: 100m
    instances: 1
    memory: "512m"
    labels:
      version: 3.0.0
    volumeMounts:
      - name: "data"
        mountPath: "/tmp/data"
      - name: "dev"
        mountPath: "/tmp/dev"
      - name: "ivy"
        mountPath: "/tmp/ivy"
