# HTTP (Netty) port for the Gateway Server to listen
server:
  port: 8080 # !!!!!!!! TEMP Change to 8081

spring:
  # Set the application name, so the service registers under this 
  # name and can also be accessed by this name 
  application:
    name: gateway-service
  cloud:
    # Enable gateway's integration with the service registry to find microservices
    gateway:
      discovery:
        locator:
          enabled: true
          # Make Service Registry name lookup be case-insensitive
          lower-case-service-id: true
      routes:
      # Account Service
      - id: account-service
        uri: lb://account-service
        predicates:
        - Path=/accounts/**
      #   # filters:
      #   # - RewritePath=/accounts/(?.*), /$\{path}
      # User Service
      - id: user-service
        uri: lb://user-service
        predicates:
        - Path=/api/users/**
      # Legacy Application
      - id: legacy-app
        uri: lb://legacy-application
        predicates:
        - Path=/api/members,/api/books,/api/members/**,/api/books/**

# Discovery Server Access
eureka:
  client:
    # URL of the Eureka Discovery Server
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/